theme: jekyll-theme-minimal
google_analytics: G-32E018B354
title : quaintitative
description: Gary Ang. Ming. Quantitative explorations in visualisation, data science, machine and deep learning here, as well as other random musings. Quantitative and quaint.
author :
  name : Gary Ang | Ming
  email : playgrdstar@gmail.com
  github : playgrdstar
  twitter : playgrdstar